#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   Displays the number of occurrences, IP, and HTTP status
#+  code of each log, in sorted order.

file_name="apache-access.log"
if test -f $file_name; then
  awk '{print $1,$9}' $file_name | sort | uniq -c | sort -gr
fi
