#!/usr/bin/env bash
# write a script that displays bad luck for the 4th loop iteration
# write a script that displays good luck for the 8th loop iteration
# write a script that displays Best School for the other iterations

count=0

while [ $count -lt 10 ]
do

if [ $count -eq 4 ]
then
	echo "bad luck"
elif [ $count -eq 8 ]
then
	echo "good luck"
else
	echo "Best School"
fi
	((count++ ))
done
